server.port=8083
spring.application.name=order-service
spring.datasource.url=jdbc:postgresql://localhost:5432/trade_flow_app
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.password=root
spring.data.redis.port=6379

#This is a eureka server so no need to register
eureka.client.register-with-eureka=true
#This is a eureka server no need to fetch registry
eureka.client.fetch-registry=true
#Register url for client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#timeout
eureka.server.wait-time-in-ms-when-sync-empty=0
spring.cloud.discovery.enabled=true
eureka.instance.prefer-ip-address=true
server.servlet.context-path=/order-service


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=order-service-id
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.topic.audit-log-reporting-topic=tf-reporting-service-log-application-event-prod
spring.kafka.topic.update-user-balance-topic=tf-user-service-debit-user-balance-prod
spring.kafka.topic.create-user-portfolio-topic=tf-order-service-create-portfolio-prod
spring.kafka.topic.market-data-update-topic=tf-market-data-subscription-updates-prod


## Exchange Server Configuration
exchange.server.base-url1=https://exchange.matraining.com
exchange.server.api-key1=21545720-c8a7-4f7e-9c3b-5fe2158a5275
exchange.server.base-url2=https://exchange2.matraining.com
exchange.server.api-key2=21545720-c8a7-4f7e-9c3b-5fe2158a5275
exchange.server.initialize-products=true